'use client';
import {useEffect,useRef,useState,useCallback} from 'react';
import Link from 'next/link';
import {W,H,BUILDINGS,WORLD_OBJECTS,NPCS,INTRO,EXTRA,RIDDLE,START} from './chapterData';
import './chapter.css';

const SAVE='clar_lost_save_ch1_story_v1';
const clone=()=>({...START,gear:{...START.gear},notes:[],talked:[]});
const dist=(x,y,a,b)=>Math.hypot(x-a,y-b);
function fill(c,x,y,w,h,color){c.fillStyle=color;c.fillRect(x,y,w,h)}
function box(c,x,y,w,h,color,edge='#44334c'){c.fillStyle=edge;c.fillRect(x-3,y-3,w+6,h+6);fill(c,x,y,w,h,color)}
function text(c,s,x,y,size=15,color='#fff0d7'){c.textAlign='center';c.font='bold '+size+'px monospace';c.fillStyle='#23172e';c.fillText(s,x+2,y+2);c.fillStyle=color;c.fillText(s,x,y)}
function light(c,x,y){const g=c.createRadialGradient(x,y,5,x,y,110);g.addColorStop(0,'#ffe7a588');g.addColorStop(1,'#ffe7a500');fill(c,x-110,y-110,220,220,g);box(c,x-4,y-36,8,51,'#52445c');box(c,x-12,y-49,24,22,'#ffe0a0')}
function bush(c,x,y){box(c,x-34,y-7,68,28,'#3d725b','#325549');box(c,x-24,y-22,43,25,'#679e79','#426e60');box(c,x+4,y-26,30,30,'#83b68b','#426e60');for(let i=0;i<5;i++)fill(c,x-19+i*9,y-19-i%2*6,4,4,'#f2c7dc')}
function person(c,x,y,hair='#a47a57',skin='#c78c76',shirt='#6d8c9d',glasses=false,t=0){c.save();c.translate(x,y+Math.sin(t/300+x)*1.5);c.fillStyle='#271b3066';c.beginPath();c.ellipse(0,19,17,6,0,0,Math.PI*2);c.fill();box(c,-14,-1,28,23,shirt);box(c,-11,20,8,7,'#393246');box(c,4,20,8,7,'#393246');box(c,-12,-30,24,30,skin);box(c,-15,-35,30,13,hair);fill(c,-15,-25,5,15,hair);fill(c,10,-25,5,11,hair);fill(c,-7,-17,4,3,'#302238');fill(c,5,-17,4,3,'#302238');if(glasses){c.strokeStyle='#32253c';c.lineWidth=2;c.strokeRect(-10,-19,10,9);c.strokeRect(3,-19,10,9);fill(c,0,-16,4,2,'#32253c')}c.restore()}
function building(c,b){const {x,y,w,h}=b;fill(c,x+10,y+25,w+20,h+35,'#231b3966');box(c,x,y+34,w,h-22,b.color);for(let i=0;i<3;i++){let wx=x+40+i*(w-80)/2;box(c,wx-20,y+87,40,49,b.id==='game'?'#77c4ca':b.id==='record'?'#b9a0ce':'#f2d0a7','#f4ddc9');fill(c,wx-2,y+88,4,46,'#fff1df')}box(c,b.doorX-24,y+129,48,60,'#584264','#f4d9bb');fill(c,b.doorX+11,y+158,5,6,'#ffe2a4');c.beginPath();c.moveTo(x-20,y+48);c.lineTo(x+14,y-15);c.lineTo(x+w-14,y-15);c.lineTo(x+w+20,y+48);c.closePath();c.fillStyle=b.roof;c.fill();c.lineWidth=6;c.strokeStyle=b.accent;c.stroke();box(c,x+19,y+10,w-38,31,'#342841','#e9bdd5');text(c,b.name,x+w/2,y+31,14);box(c,b.doorX-34,y+h+6,68,17,'#6b5775','#a18ca0');text(c,'ENTER',b.doorX,y+h+19,11)}
function town(c,p,t,glitch){const bg=c.createLinearGradient(0,0,0,H);bg.addColorStop(0,glitch?'#15101f':'#697393');bg.addColorStop(1,glitch?'#252033':'#c1aaa8');fill(c,0,0,W,H,bg);fill(c,0,248,W,190,glitch?'#383043':'#d0bfc0');fill(c,477,238,166,402,glitch?'#383043':'#d0bfc0');for(let i=0;i<W;i+=54){fill(c,i,248,2,190,glitch?'#514257':'#b09da9')}for(let i=245;i<H;i+=44)fill(c,477,i,166,2,glitch?'#514257':'#e7d4d0');for(let i=0;i<16;i++)bush(c,(i*79+22)%W,i%2?606:30);for(const b of BUILDINGS)building(c,b);if(!glitch)for(const [x,y] of [[50,280],[350,264],[711,270],[1020,275],[425,520],[745,530]])light(c,x,y);box(c,507,286,102,126,'#8a7793','#f0d9c4');box(c,521,302,74,76,'#f3dcbb','#634c71');c.strokeStyle='#4c3b58';c.lineWidth=5;c.beginPath();c.arc(558,338,27,0,Math.PI*2);c.stroke();c.beginPath();c.moveTo(558,338);c.lineTo(543,318);c.moveTo(558,338);c.lineTo(574,349);c.stroke();text(c,'11:19',558,398,16);box(c,516,451,83,54,glitch?'#4b3d57':'#91c5c8','#eee1cf');text(c,'✦',558,483,27);if(!p.letter){c.save();c.translate(166,451);c.rotate(-.13);box(c,-22,-15,44,30,'#f8e8d0','#a28083');c.strokeStyle='#a28083';c.lineWidth=2;c.beginPath();c.moveTo(-21,-14);c.lineTo(0,5);c.lineTo(21,-14);c.stroke();fill(c,-4,1,9,8,'#c27992');c.restore()}bush(c,804,475);box(c,48,509,65,91,'#b7a6bd','#ebd5e5');box(c,58,520,45,66,glitch?'#2a2135':'#80789e','#ead8e9');text(c,'?',80,563,32);box(c,1016,307,94,129,glitch?'#38273e':'#604c71','#e7c4dc');box(c,1031,324,64,95,'#392e51','#b89abb');text(c,'EXIT',1063,298,20);text(c,'✧',1063,375,31);box(c,332,307,60,55,'#b29c9c','#f1d9bd');text(c,'?',362,343,28);if(!glitch){person(c,p.x,p.y,'#b07e54','#c89d80','#667b91',true,t);text(c,'CLAR',p.x,p.y-53,15)}else{person(c,708,385,'#10111a','#12101b','#11111b',false,t);fill(c,698,366,5,5,'#e35baf');fill(c,710,366,5,5,'#e35baf');for(let i=0;i<26;i++)fill(c,(i*107+t/7)%W,(i*69+t/20)%H,48,3,i%2?'#dd6ca766':'#78d5d055')}const g=c.createRadialGradient(560,330,140,560,330,760);g.addColorStop(0,'#0000');g.addColorStop(1,glitch?'#090511d9':'#20132a88');fill(c,0,0,W,H,g)}
function shop(c,p,t){const s=p.scene;const bg=c.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#47364f');bg.addColorStop(.62,'#78617a');bg.addColorStop(.63,'#b59a9b');bg.addColorStop(1,'#66576e');fill(c,0,0,W,H,bg);box(c,35,25,W-70,348,'#5c4966','#b59bb2');for(let i=0;i<9;i++){box(c,75+i*108,65,81,286,'#675470','#927f98');if(s==='record')for(let j=0;j<3;j++){box(c,85+i*108,110+j*71,61,55,['#d3a1b7','#91b9cb','#e2c99c'][j]);c.strokeStyle='#3e3151';c.lineWidth=4;c.beginPath();c.arc(115+i*108,137+j*71,18,0,Math.PI*2);c.stroke()}if(s==='bakery')for(let j=0;j<3;j++){box(c,86+i*108,133+j*70,58,25,'#d9a87d','#f3d0a0');text(c,'◡',115+i*108,147+j*70,22)}if(s==='game'){box(c,82+i*108,125,65,104,'#3c4964','#c3bed8');text(c,'1UP',114+i*108,183,17,'#a5e7d7')}}text(c,s==='bakery'?'MOONCRUMB · BAKERY':s==='record'?'SIDE B · RECORDS':'PIXEL PALACE · GAME STORE',560,44,25);if(s==='record'){box(c,952,270,125,185,'#3c2b50','#d4b3cf');text(c,'BACK ROOM',1014,316,15);text(c,p.keyGiven?'OPEN':'LOCKED',1014,392,16,p.keyGiven?'#b8e5ce':'#eab4c4')}if(s==='record'&&p.backRoom){box(c,225,85,670,262,'#332640','#dfb2d2');text(c,'BACK ROOM / CORRUPTED MESSAGE',560,125,22);text(c,'WHEN THE CLOCK STOPS,',560,202,21,'#ffe0bd');text(c,'FOLLOW THE REFLECTION.',560,242,21,'#ffe0bd')}else{const ids=s==='bakery'?['naidu']:s==='record'?['riri','trisha']:['aaron','lakshay'];for(const id of ids){const n=NPCS[id];person(c,n.x,n.y,n.hair,n.skin,n.outfit,false,t);text(c,n.name,n.x,n.y-54,16)}}person(c,p.x,p.y,'#b07e54','#c89d80','#667b91',true,t);text(c,'CLAR',p.x,p.y-53,15);box(c,470,543,183,70,'#705679','#e3bcd2');text(c,'← LEAVE SHOP',562,582,18);const g=c.createRadialGradient(560,270,180,560,320,700);g.addColorStop(0,'#0000');g.addColorStop(1,'#170e26b0');fill(c,0,0,W,H,g)}
function Icon({id}){return <svg viewBox="0 0 80 80" width="64" height="64" aria-label={id}>{id==='letter'?<><rect x="11" y="22" width="58" height="39" rx="3" fill="#f8e6c9" stroke="#a68185" strokeWidth="3"/><path d="M12 24L40 46 68 24" fill="none" stroke="#a68185" strokeWidth="3"/><rect x="36" y="43" width="11" height="9" fill="#c27893"/></>:id==='key'?<><circle cx="25" cy="27" r="13" fill="none" stroke="#efd28e" strokeWidth="9"/><path d="M35 37L66 66 72 59 63 51 66 45 58 40 54 47 42 34" fill="#efd28e"/></>:id==='flashlight'?<><path d="M20 40L42 26 56 37 41 52 35 69 22 65Z" fill="#c5d9dc" stroke="#6c7d8d" strokeWidth="4"/><path d="M42 24L60 14 73 31 56 43Z" fill="#f1d997"/><circle cx="64" cy="27" r="7" fill="#fff9bc"/></>:id==='headphones'?<><path d="M17 48V35C17 5 63 5 63 35V48" fill="none" stroke="#e5b4d9" strokeWidth="10"/><rect x="10" y="40" width="18" height="28" rx="6" fill="#9277b6"/><rect x="52" y="40" width="18" height="28" rx="6" fill="#9277b6"/></>:id==='journal'?<><rect x="16" y="10" width="51" height="60" rx="5" fill="#9176ad" stroke="#e6c9e7" strokeWidth="4"/><rect x="24" y="12" width="6" height="56" fill="#524075"/><path d="M37 30H56M37 40H56M37 50H51" stroke="#fff0dd" strokeWidth="3"/></>:<><path d="M56 8L68 9 64 21 38 53 30 44Z" fill="#d7e5e5" stroke="#839ba4" strokeWidth="3"/><path d="M22 39L43 60" stroke="#d2a7cc" strokeWidth="8"/><path d="M28 52L14 66" stroke="#9c7966" strokeWidth="9"/></>}</svg>}
function Portrait({id}){const n=NPCS[id];if(!n)return <div className="ch1-symbol">✦</div>;return <div className="ch1-portrait" style={{background:'linear-gradient(145deg,'+n.color+',#40324e)'}}><div className="ch1-portrait-hair" style={{background:n.hair}}/><div className="ch1-portrait-face" style={{background:n.skin}}><div className="ch1-portrait-eyes">▪　▪</div><div className="ch1-portrait-mouth">{n.expression==='animated'?'◡':n.expression==='worried'?'﹏':'—'}</div></div><div className="ch1-portrait-body" style={{background:n.outfit}}/><div className="ch1-portrait-name">{n.name}</div></div>}
const labels={letter:'FOLDED LETTER',key:'BRASS KEY',flashlight:'FLASHLIGHT',headphones:'HEADPHONES',journal:'JOURNAL',sword:'PRACTICE SWORD'};
export default function ChapterOne(){
 const [p,setP]=useState(clone),ref=useRef(p),[loaded,setLoaded]=useState(false),[dialog,setDialog]=useState(null),dialogRef=useRef(null),[typed,setTyped]=useState(0),[panel,setPanel]=useState(null),panelRef=useRef(null),[toast,setToast]=useState(''),[music,setMusic]=useState(false),[glitch,setGlitch]=useState(false),glitchRef=useRef(false),[count,setCount]=useState(10);
 const canvas=useRef(null),held=useRef(new Set()),audio=useRef(null);
 useEffect(()=>{try{const v=JSON.parse(localStorage.getItem(SAVE)||'null');if(v&&v.gear&&Number.isFinite(v.x)){const q={...clone(),...v,gear:{...START.gear,...v.gear},notes:Array.isArray(v.notes)?v.notes:[],talked:Array.isArray(v.talked)?v.talked:[]};setP(q);ref.current=q}}catch{}setLoaded(true)},[]);
 useEffect(()=>{ref.current=p;if(loaded)try{localStorage.setItem(SAVE,JSON.stringify(p))}catch{}},[p,loaded]);
 useEffect(()=>{dialogRef.current=dialog},[dialog]);useEffect(()=>{panelRef.current=panel},[panel]);
 const patch=useCallback(fn=>setP(q=>{const v=typeof fn==='function'?fn(q):{...q,...fn};ref.current=v;return v}),[]);
 const note=useCallback(s=>patch(q=>({...q,notes:q.notes.includes(s)?q.notes:[...q.notes,s]})),[patch]);
 const beep=useCallback((freq=520,dur=.15,type='sine',vol=.04)=>{try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;if(!audio.current)audio.current=new A();const a=audio.current;a.resume();const o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,a.currentTime);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+dur);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+dur)}catch{}},[]);
 useEffect(()=>{if(!music||glitch)return;const seq=[261,329,392,329,293,349,440,349,261,329,392,523,440,392,329,293];let i=0;const t=setInterval(()=>beep(seq[i++%seq.length],.3,'sine',.012),345);return()=>clearInterval(t)},[music,glitch,beep]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3400);return()=>clearTimeout(t)},[toast]);
 const say=useCallback((who,lines,done)=>{setPanel(null);setDialog({who,lines:Array.isArray(lines)?lines:[lines],index:0,done})},[]);
 useEffect(()=>{if(!dialog)return;setTyped(0);const line=dialog.lines[dialog.index];const t=setInterval(()=>setTyped(n=>Math.min(n+2,line.length)),23);return()=>clearInterval(t)},[dialog]);
 const next=()=>{const d=dialogRef.current;if(!d)return;const line=d.lines[d.index];if(typed<line.length){setTyped(line.length);return}if(d.index<d.lines.length-1){setDialog({...d,index:d.index+1});return}setDialog(null);d.done?.()};
 const talk=useCallback(id=>{const v=ref.current;if(!v.talked.includes(id)){patch(q=>({...q,talked:[...q.talked,id]}));say(id,INTRO[id],()=>{if(id==='aaron'&&!ref.current.gear.flashlight){patch(q=>({...q,gear:{...q.gear,flashlight:true}}));note('Aaron gave me a working flashlight.');setToast('NEW ITEM · FLASHLIGHT')}if(id==='lakshay'&&!ref.current.gear.journal){patch(q=>({...q,gear:{...q.gear,headphones:true,journal:true,sword:true}}));note('Lakshay gave me headphones, a journal and a wooden practice sword.');setToast('NEW ITEMS · HEADPHONES · JOURNAL · SWORD')}});return}
 if(id==='naidu'&&v.letter&&!v.letterGiven){say(id,['You found my letter! Thank you, Clar. I thought the town had swallowed it.','It says: “When the clocks stop, the people who remember you will still find you.”','I think that might matter more than we realise.'],()=>{patch(q=>({...q,letterGiven:true}));note('Returned Naidu’s letter. The message is about remembering people.');beep(740,.3)});return}
 if((id==='riri'||id==='trisha')&&v.key&&!v.keyGiven){say(id,['That is our key! You actually found it!','We saw a strange mirror at the southwest corner of town. It appeared after the clock froze.','Look into it before you try to leave. It might know what the gate wants.'],()=>{patch(q=>({...q,keyGiven:true}));note('Returned the back-room key. Riri and Trisha pointed me toward a mirror in the southwest.');beep(740,.3)});return}
 say(id,EXTRA[id][v.letterGiven||v.keyGiven?0:1]);},[patch,say,note,beep]);
 const interact=useCallback(id=>{if(dialogRef.current||panelRef.current||glitchRef.current)return;const v=ref.current;
 if(NPCS[id]){talk(id);return}if(BUILDINGS.some(b=>b.id===id)){patch(q=>({...q,scene:id,backRoom:false,x:558,y:500}));beep();return}
 if(id==='leave'){patch(q=>({...q,scene:'town',backRoom:false,x:BUILDINGS.find(b=>b.id===v.scene)?.doorX||558,y:271}));return}
 if(id==='back'){if(!v.keyGiven){say('LOCKED DOOR','A brass keyhole. Maybe Riri and Trisha know where the key went.');return}patch(q=>({...q,backRoom:true,x:558,y:490}));note('In the record shop back room: “When the clock stops, follow the reflection.”');return}
 if(id==='clock'){patch(q=>({...q,clock:true}));note('The clock is frozen at exactly 11:19.');setPanel('clock');beep(410,.25);return}
 if(id==='letter'){if(v.letter)return;patch(q=>({...q,letter:true}));note('Found Naidu’s folded envelope by the western path.');setToast('FOUND · FOLDED LETTER');beep(680,.25);return}
 if(id==='bush'){if(v.key){setToast('Nothing else hidden in this bush.');return}patch(q=>({...q,key:true}));note('Found the brass key hidden inside a bush east of the square.');say('CLAR',['Something glints beneath the leaves...','A little brass key! It was completely hidden in the bush.']);beep(750,.25);return}
 if(id==='mirror'){patch(q=>({...q,mirror:true}));note('The mirror says memories—not clocks, weapons or keys—open the exit.');setPanel('mirror');beep(390,.3,'triangle');return}
 if(id==='exit'){if(!v.clock){say('TOWN EXIT','The door says: “Look closely at the clock before leaving.”');return}if(!v.mirror){say('TOWN EXIT','The door says: “The mirror in the southwest remembers the answer.”');return}setPanel('riddle');return}
 if(id==='fountain')say('CLAR',['The fountain has run dry. Nineteen tiny hearts are scratched into the stone.']);
 if(id==='sign')say('TOWN NOTICE',['WELCOME TO STILLWATER. POPULATION: ERROR.','PLEASE DO NOT ASK THE CLOCK WHAT TIME IT IS.']);
 },[patch,talk,say,note,beep]);
 const clickCanvas=e=>{if(panelRef.current||dialogRef.current||glitchRef.current)return;const r=canvas.current.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height,v=ref.current;if(v.scene==='town'){for(const b of BUILDINGS)if(x>b.x&&x<b.x+b.w&&y>b.y-15&&y<b.y+b.h+30){interact(b.id);return}for(const o of WORLD_OBJECTS)if(dist(x,y,o.x,o.y)<o.r+13){interact(o.id);return}}else{if(y>530&&x>460&&x<665){interact('leave');return}if(v.scene==='record'&&x>940&&y>265&&y<475){interact('back');return}if(!v.backRoom)for(const [id,n] of Object.entries(NPCS))if(n.shop===v.scene&&dist(x,y,n.x,n.y)<75){interact(id);return}}};
 const near=useCallback(()=>{const v=ref.current;if(v.scene==='town'){const o=[...WORLD_OBJECTS.map(a=>({id:a.id,d:dist(v.x,v.y,a.x,a.y)})),...BUILDINGS.map(b=>({id:b.id,d:dist(v.x,v.y,b.doorX,b.y+b.h+16)}))].sort((a,b)=>a.d-b.d);if(o[0]?.d<110)interact(o[0].id);else setToast('Move closer to an object, or tap it directly.');return}if(v.y>480){interact('leave');return}if(v.scene==='record'&&v.x>910){interact('back');return}const o=Object.entries(NPCS).filter(([,n])=>n.shop===v.scene).map(([id,n])=>({id,d:dist(v.x,v.y,n.x,n.y)})).sort((a,b)=>a.d-b.d);if(o[0]?.d<140)interact(o[0].id);else setToast('Move closer to a friend, or tap them directly.')},[interact]);
 const walk=(v,x,y)=>{if(x<25||x>W-25||y<255||y>H-27)return false;if(v.scene==='town'){for(const b of BUILDINGS)if(x>b.x-18&&x<b.x+b.w+18&&y>b.y-18&&y<b.y+b.h+14)return false;for(const o of WORLD_OBJECTS)if(['clock','fountain','exit'].includes(o.id)&&dist(x,y,o.x,o.y)<o.r+16)return false}else if(y<375)return false;return true};
 useEffect(()=>{const down=e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d','e',' '].includes(k))e.preventDefault();if(k==='e'||k===' '){if(!dialogRef.current&&!panelRef.current)near()}else held.current.add(k)},up=e=>held.current.delete(e.key.toLowerCase());window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up)}},[near]);
 useEffect(()=>{let frame,last=0,steps=0;const loop=t=>{frame=requestAnimationFrame(loop);if(t-last<30)return;last=t;const c=canvas.current?.getContext('2d');if(!c)return;const v=ref.current;if(!panelRef.current&&!dialogRef.current&&!glitchRef.current){let dx=0,dy=0;const k=held.current;if(k.has('arrowup')||k.has('w'))dy--;if(k.has('arrowdown')||k.has('s'))dy++;if(k.has('arrowleft')||k.has('a'))dx--;if(k.has('arrowright')||k.has('d'))dx++;if(dx||dy){const m=3.8/Math.hypot(dx,dy),x=v.x+dx*m,y=v.y+dy*m;if(walk(v,x,y)){v.x=x;v.y=y;if(++steps%5===0)patch(q=>({...q,x,y}))}}}c.clearRect(0,0,W,H);if(v.scene==='town')town(c,v,t,glitchRef.current);else shop(c,v,t);if(v.flashOn&&!glitchRef.current){const g=c.createRadialGradient(v.x,v.y,3,v.x,v.y,200);g.addColorStop(0,'#ffe5a766');g.addColorStop(1,'#ffe5a700');fill(c,v.x-200,v.y-200,400,400,g)}if(v.headphonesOn&&!glitchRef.current)text(c,'♫ HIDDEN SIGNAL: 11:19 / REMEMBER',560,20,15,'#c5f7dc')};frame=requestAnimationFrame(loop);return()=>cancelAnimationFrame(frame)},[patch]);
 const glitchNow=()=>{glitchRef.current=true;setGlitch(true);setPanel(null);setCount(10);patch(q=>({...q,scene:'town',x:560,y:490,gateSolved:true}));note('The gate opened. All the lights died. Everyone vanished. The Watcher warned me.');for(let i=0;i<7;i++)setTimeout(()=>beep(80+i*38,.42,i%2?'sawtooth':'square',.06),i*180);let n=10;const id=setInterval(()=>{n--;setCount(n);if(n<=0){clearInterval(id);glitchRef.current=false;setGlitch(false);patch(q=>({...q,complete:true}));setPanel('clear');beep(740,.4)}},1000)};
 const answer=i=>{if(i===RIDDLE.correct)glitchNow();else{beep(150,.2,'square');setToast('WRONG ANSWER · Remember the mirror’s hint.')}};
 const useItem=id=>{if(id==='journal'){setPanel('journal');return}if(id==='flashlight')patch(q=>({...q,flashOn:!q.flashOn}));if(id==='headphones')patch(q=>({...q,headphonesOn:!q.headphonesOn}));if(id==='sword')patch(q=>({...q,swordOn:!q.swordOn}));beep()};
 const items=[...(p.letter&&!p.letterGiven?['letter']:[]),...(p.key&&!p.keyGiven?['key']:[]),...Object.keys(p.gear).filter(k=>p.gear[k])];
 const objective=p.complete?'Chapter 1 completed.':!p.clock?'Inspect the frozen clock at the town square.':!p.keyGiven?'Explore the shops, find the letter and hidden key.':!p.mirror?'Find the mysterious mirror in the southwest corner.':'Use the mirror’s hint to solve the exit riddle.';
 const restart=()=>{if(!window.confirm('Restart Chapter 1 and overwrite this chapter save?'))return;patch(clone());setPanel(null);setDialog(null)};
 return <main className="ch1-root"><header className="ch1-header"><div><small>CLAR_OS / THE LOST SAVE FILE</small><h1>01 · THE GLITCHED TOWN</h1></div><div className="ch1-headright"><span>CHAPTER ONE · AUTOSAVED</span><button className="ch1-button" onClick={()=>{setMusic(x=>!x);beep()}}>{music?'♫ MUSIC ON':'♪ PLAY MUSIC'}</button></div></header>
 <div className="ch1-stage"><canvas ref={canvas} width={W} height={H} onClick={clickCanvas} aria-label="Interactive town, shops and characters. Tap to interact."/><div className="ch1-scene-name">{p.scene==='town'?'STILLWATER / THE TOWN THAT FORGOT':BUILDINGS.find(b=>b.id===p.scene)?.name}</div>{glitch&&<div className="ch1-glitch"><strong>WATCH OUT, CLAR_</strong><span>RECOVERING IN {count}s</span></div>}</div>
 <div className="ch1-bottom"><div className="ch1-objective"><b>OBJECTIVE:</b> {objective}<small>WASD / arrow keys / touch to move · Tap shops, people and objects · E to interact</small></div><div className="ch1-controls"><div className="ch1-dpad"><span/><button className="ch1-button" onPointerDown={e=>{e.preventDefault();held.current.add('arrowup')}} onPointerUp={()=>held.current.delete('arrowup')} onPointerCancel={()=>held.current.delete('arrowup')}>▲</button><span/>{[['◀','arrowleft'],['▼','arrowdown'],['▶','arrowright']].map(([s,k])=><button key={k} className="ch1-button" onPointerDown={e=>{e.preventDefault();held.current.add(k)}} onPointerUp={()=>held.current.delete(k)} onPointerCancel={()=>held.current.delete(k)}>{s}</button>)}</div><button className="ch1-button" onClick={near}>✦ INTERACT</button><button className="ch1-button" onClick={()=>setPanel('inventory')}>▣ INVENTORY {items.length}</button><button className="ch1-button" onClick={()=>setPanel('journal')}>▤ JOURNAL</button></div></div>
 <p className="ch1-tip">TIP: Tap a shop to enter. Tap the clock to zoom in. The letter is an envelope; the key is hidden in a bush.</p>
 {dialog&&<div className="ch1-overlay"><section className="ch1-modal"><small>✦ TRANSMISSION · {dialog.index+1}/{dialog.lines.length}</small><div className="ch1-dialog"><Portrait id={dialog.who}/><div><h2>{NPCS[dialog.who]?.name||dialog.who}</h2><p>{dialog.lines[dialog.index].slice(0,typed)}{typed<dialog.lines[dialog.index].length&&<span className="ch1-cursor">▌</span>}</p></div></div><div className="ch1-actions"><button className="ch1-button" onClick={next}>{typed<dialog.lines[dialog.index].length?'SHOW FULL LINE ▸':dialog.index<dialog.lines.length-1?'CONTINUE ▸':'FINISH CONVERSATION ✓'}</button></div></section></div>}
 {panel&&<div className="ch1-overlay"><section className="ch1-modal"><small>CLAR_OS / {panel.toUpperCase()}</small>
 {panel==='clock'&&<><h2>THE FROZEN CLOCK</h2><div className="ch1-clock">{Array.from({length:12},(_,i)=><span key={i} style={{transform:'rotate('+(i*30)+'deg) translateY(-114px) rotate('+(-i*30)+'deg)'}}>{i||12}</span>)}<i className="hour"/><i className="minute"/><i className="pin"/></div><h3 style={{textAlign:'center'}}>11:19</h3><p>Its second hand is perfectly still. The town has been holding its breath at this exact minute.</p></>}
 {panel==='mirror'&&<><h2>THE MIRROR THAT REMEMBERS</h2><div className="ch1-mirror">◈</div><p>{RIDDLE.hint}</p><p>Clar's reflection moves a second before she does.</p></>}
 {panel==='riddle'&&<><h2>THE EXIT / FOUR ANSWERS</h2><p>{RIDDLE.question}</p><div className="ch1-answers">{RIDDLE.answers.map((a,i)=><button className="ch1-button" key={i} onClick={()=>answer(i)}>{['A','B','C','D'][i]}. {a}</button>)}</div><small>The mirror in the southwest knows the answer.</small></>}
 {panel==='inventory'&&<><h2>CLAR'S INVENTORY</h2>{items.length?<div className="ch1-items">{items.map(id=><button key={id} className={'ch1-item '+((id==='flashlight'&&p.flashOn)||(id==='headphones'&&p.headphonesOn)||(id==='sword'&&p.swordOn)?'active':'')} onClick={()=>useItem(id)}><Icon id={id}/><b>{labels[id]}</b><small>{id==='journal'?'OPEN NOTES':id==='flashlight'?(p.flashOn?'ON':'TAP TO SWITCH ON'):id==='headphones'?(p.headphonesOn?'EQUIPPED':'TAP TO EQUIP'):id==='sword'?(p.swordOn?'EQUIPPED':'TAP TO EQUIP'):'QUEST ITEM'}</small></button>)}</div>:<p>Empty. Talk to Aaron and Lakshay at the game store to collect useful gear.</p>}<p>Flashlight, headphones, journal and sword are interactive. The sword is equippable, but Chapter 1 has no combat.</p></>}
 {panel==='journal'&&<><h2>CLAR'S JOURNAL</h2><p>{objective}</p>{(p.notes.length?p.notes:['The town seems familiar. I should investigate the shops.']).map((s,i)=><div className="ch1-note" key={i}>{String(i+1).padStart(2,'0')} / {s}</div>)}</>}
 {panel==='clear'&&<><h2>CHAPTER 1 COMPLETE ♡</h2><div className="ch1-ending">✦ 11:19 ✦</div><p>The lights come back. The streets are normal. Your friends have returned.</p><p>But the Watcher's warning remains: <b>“Watch out, Clar. The next place remembers things differently.”</b></p><p>Chapter 2 has deliberately not been built yet. Your Chapter 1 progress is saved.</p><div className="ch1-actions"><Link href="/lost-save-file" className="ch1-button">VIEW ORIGINAL RPG</Link></div></>}
 <div className="ch1-actions"><button className="ch1-button" onClick={()=>setPanel(null)}>✕ CLOSE</button></div></section></div>}
 {toast&&<div className="ch1-toast" role="status">{toast}</div>}
 <footer className="ch1-footer"><span>NEW CHAPTER 1 PREVIEW · Original RPG unchanged · rpg-experiment branch</span><button onClick={restart}>Restart chapter</button><Link href="/lost-save-file">Original prototype ↗</Link></footer>
 </main>
}
