'use client'
import {useEffect,useRef,useState} from 'react'

const W=16,H=11,T=38
const walls=new Set()
for(let x=0;x<W;x++){walls.add(x+',0');walls.add(x+','+(H-1))}
for(let y=0;y<H;y++){walls.add('0,'+y);walls.add((W-1)+','+y)}
for(let y=2;y<9;y++)if(y!==5)walls.add('10,'+y)
const friends=[{x:4,y:3,n:'TRISHA',c:'#f4a9d5',line:'Riri and I found something weird near the old archive.'},{x:5,y:3,n:'RIRI',c:'#c3a2ff',line:'I swear the hallway moved when nobody was looking.'},{x:3,y:8,n:'NUT',c:'#8ce2d5',line:'Five coins? I would sell you a map, but I lost it.'},{x:8,y:8,n:'LIMIN',c:'#f3cb8c',line:'The clock has been stuck at 11:19 all day.'}]
const initialCoins=['2,2','7,2','6,7','9,4','12,8','13,3','4,7']
const keyAt='8,3',chestAt='3,6',doorAt='10,5',mirrorAt='6,2'
const keyOf=(p)=>p.x+','+p.y
export default function LostSaveFile(){
 const [started,setStarted]=useState(false),[hair,setHair]=useState('#30233c'),[outfit,setOutfit]=useState('#c078d8')
 const [pos,setPos]=useState({x:2,y:5}),[coins,setCoins]=useState([]),[gold,setGold]=useState(0),[hasKey,setHasKey]=useState(false),[open,setOpen]=useState(false),[talked,setTalked]=useState([]),[dialog,setDialog]=useState(null),[shadow,setShadow]=useState(false),[caught,setCaught]=useState(false),[fragment,setFragment]=useState(false)
 const posRef=useRef(pos);posRef.current=pos
 const move=(dx,dy)=>{if(!started||dialog)return;const p=posRef.current,n={x:p.x+dx,y:p.y+dy},k=keyOf(n);if(walls.has(k))return;if(k===doorAt&&!open){setDialog({who:'ARCHIVE DOOR',text:'LOCKED. Find the rusted key and tap INTERACT beside this door.'});return}setPos(n);if(initialCoins.includes(k)&&!coins.includes(k)){setCoins(v=>[...v,k]);setGold(v=>v+1)}if(open&&n.x>10&&!shadow&&!fragment){setShadow(true);setDialog({who:'SYSTEM WARNING',text:'Something is moving in the archive. Avoid the shadow and find the memory fragment at the far end.'})}if(shadow&&n.x>=12&&n.y===6&&!fragment){setCaught(true);setPos({x:9,y:5});setDialog({who:'SAVE FILE ERROR',text:'YOU WERE NOT SUPPOSED TO SEE THAT. You wake at the checkpoint. Your items are safe.'})}if(n.x===14&&n.y===5&&open){setFragment(true);setShadow(false);setDialog({who:'MEMORY RESTORED',text:'You recovered a memory fragment! The world remembers you. Prototype complete — more chapters coming soon.'})}}
 const interact=()=>{if(!started||dialog)return;const p=posRef.current,near=(x,y)=>Math.abs(p.x-x)+Math.abs(p.y-y)<=1;const friend=friends.find(f=>near(f.x,f.y));if(friend){setTalked(v=>v.includes(friend.n)?v:[...v,friend.n]);setDialog({who:friend.n,text:friend.line});return}if(near(8,3)&&!hasKey){setHasKey(true);setDialog({who:'ITEM FOUND',text:'You picked up a RUSTED KEY. Maybe it opens the archive door.'});return}if(near(10,5)){if(hasKey){setOpen(true);setDialog({who:'ARCHIVE UNLOCKED',text:'The old lock clicks open. The lights inside flicker.'})}else setDialog({who:'LOCKED',text:'A rusty keyhole. Search the town.'});return}if(near(3,6)){setGold(v=>v+3);setDialog({who:'TREASURE CHEST',text:'You found 3 coins! (This demo chest can be reopened.)'});return}if(near(6,2)){setDialog({who:'MIRROR.exe',text:'Your reflection is wearing a different outfit. It smiles a second too late.'});return}setDialog({who:'CLAR',text:'Nothing interesting here... yet.'})}
 useEffect(()=>{const onKey=e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','e','E'].includes(e.key))e.preventDefault();if(e.key==='ArrowUp'||e.key==='w')move(0,-1);if(e.key==='ArrowDown'||e.key==='s')move(0,1);if(e.key==='ArrowLeft'||e.key==='a')move(-1,0);if(e.key==='ArrowRight'||e.key==='d')move(1,0);if(e.key==='e'||e.key==='E'||e.key===' ')interact()};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)})
 const cell=(x,y)=>{const k=x+','+y;const f=friends.find(f=>f.x===x&&f.y===y);let bg=(x+y)%2?'#30213f':'#372747';if(x>10)bg=(x+y)%2?'#181523':'#24182c';if(walls.has(k))bg='#100c19';const here=pos.x===x&&pos.y===y;return <div key={k} style={{position:'relative',background:bg,border:'1px solid #ffffff08',display:'grid',placeItems:'center',fontSize:21,overflow:'hidden'}}>{k===doorAt?<span style={{color:open?'#80e7d0':'#e6b4e9'}}>{open?'▯':'🚪'}</span>:null}{k===chestAt?'📦':null}{k===mirrorAt?'🪞':null}{k===keyAt&&!hasKey?'🗝️':null}{initialCoins.includes(k)&&!coins.includes(k)?'🪙':null}{f?<span title={f.n} style={{color:f.c,fontSize:23}}>♟</span>:null}{x===14&&y===5&&!fragment?'💎':null}{shadow&&x===12&&y===6?'👁️':null}{here?<div style={{position:'absolute',width:20,height:26,background:outfit,border:'3px solid #161021',borderRadius:5,boxShadow:'0 0 0 2px #f5d3ef',zIndex:2}}><div style={{position:'absolute',width:15,height:12,background:hair,top:-9,left:0,borderRadius:5}}/></div>:null}</div>}
 const btn={background:'#6e3991',border:'1px solid #c690e9',color:'#fff',borderRadius:7,padding:'12px 15px',font:'inherit',touchAction:'manipulation'}
 return <main style={{minHeight:'100dvh',background:'radial-gradient(circle at 50% 20%,#301741,#0d0817 70%)',color:'#f3d9ff',fontFamily:'ui-monospace,Menlo,monospace',padding:'18px 12px 35px',boxSizing:'border-box'}}>
 <div style={{maxWidth:780,margin:'auto'}}><p style={{fontSize:11,color:'#9ee7e1',letterSpacing:3}}>CLAR_OS / ARCADE / EXPERIMENTAL BUILD</p><h1 style={{fontSize:'clamp(19px,4vw,29px)',margin:'6px 0'}}>THE LOST SAVE FILE.exe</h1><p style={{fontSize:12,color:'#d1a9df'}}>🪙 {gold} COINS　🗝️ {hasKey?'1 KEY':'0 KEY'}　👥 {talked.length}/4 FRIENDS　💎 {fragment?'1':'0'} MEMORY</p>
 {!started?<section style={{border:'2px solid #a16bc2',background:'#21122e',padding:24,marginTop:24}}><h2>CREATE_PLAYER.exe</h2><p>Hi Clar. Before the world remembers you, choose a look.</p><label>HAIR　<select value={hair} onChange={e=>setHair(e.target.value)} style={{...btn,margin:8}}><option value="#30233c">Dark</option><option value="#a65b42">Auburn</option><option value="#e9c68d">Blonde</option></select></label><br/><label>OUTFIT　<select value={outfit} onChange={e=>setOutfit(e.target.value)} style={{...btn,margin:8}}><option value="#c078d8">Purple</option><option value="#79c9c5">Teal</option><option value="#e9a2b4">Pink</option></select></label><p><button style={btn} onClick={()=>setStarted(true)}>▶ ENTER THE LOST SAVE FILE</button></p></section>:<>
 <div style={{overflowX:'auto',border:'2px solid #9861bc',marginTop:18,background:'#130e1b'}}><div style={{display:'grid',gridTemplateColumns:'repeat(16,38px)',gridTemplateRows:'repeat(11,38px)',width:608,margin:'auto'}}>{Array.from({length:W*H},(_,i)=>cell(i%W,Math.floor(i/W)))}</div></div>
 <p style={{fontSize:12,color:'#b6a5c4'}}>Find coins, speak to friends (♟), pick up the key 🗝️, unlock the archive 🚪, and reach the fragment 💎.</p>
 <div style={{display:'flex',gap:15,flexWrap:'wrap',justifyContent:'center',alignItems:'center',marginTop:14}}><div style={{display:'grid',gridTemplateColumns:'repeat(3,54px)',gap:5}}><span/><button style={btn} onClick={()=>move(0,-1)}>▲</button><span/><button style={btn} onClick={()=>move(-1,0)}>◀</button><button style={btn} onClick={()=>move(0,1)}>▼</button><button style={btn} onClick={()=>move(1,0)}>▶</button></div><button style={{...btn,minHeight:62}} onClick={interact}>✦ INTERACT</button><button style={{...btn,minHeight:62}} onClick={()=>setDialog({who:'INVENTORY',text:'Coins: '+gold+' | Rusted key: '+(hasKey?'YES':'NO')+' | Memory fragment: '+(fragment?'YES':'NO')+' | Friends met: '+(talked.join(', ')||'none')})}>🎒 INVENTORY</button></div>
 </>}
 {dialog&&<div style={{position:'fixed',inset:0,background:'#09050bc9',display:'grid',placeItems:'center',zIndex:50,padding:20}}><div style={{background:'#271535',border:'2px solid #b478d5',maxWidth:480,width:'100%',padding:24,boxSizing:'border-box',boxShadow:'0 0 45px #8b3bb055'}}><h3 style={{color:'#a4e6df',marginTop:0}}>{dialog.who}</h3><p style={{lineHeight:1.6}}>{dialog.text}</p><button style={btn} onClick={()=>setDialog(null)}>CONTINUE ▸</button></div></div>}
 </div></main>
}
