// Narrative data for the experimental RPG. Original placeholder story scenes.
// No data is loaded from CLAR_OS, and no production files are changed.
export const FRIEND_ARCS=[
 {name:'Naidu',title:'The letter that was never sent',target:'item:letter',request:'I wrote something down before the town started forgetting. The folded letter is near the bakery. Bring it back; I want to read it with you.',ready:'You found it? I thought the town had eaten the whole street.',finish:'It says: "If you get lost, follow the people who still call you by your name." I think I wrote that for you.',clue:'The town clock and the letter remember the same evening.'},
 {name:'Yanaal',title:'Eleven nineteen',target:'item:clock',request:'The clock by the southern lane has stopped. Find out what time it remembers. I need to know whether we are early or impossibly late.',ready:'Eleven nineteen? That is so specific it is actually rude.',finish:'The clock was not counting hours. It was keeping a date alive. The first memory seal should understand that.',clue:'The clock reads 11:19.'},
 {name:'Nesma',title:'Mirror with a missing reflection',target:'item:mirror',request:'Find the broken mirror north of the street. Please tell me whether it reflects the sky or the room behind you.',ready:'It showed a room that is not there? Interesting. Horrible. But interesting.',finish:'I saw another Clar in the glass. She looked relieved you came back.',clue:'The reflection changes after the memory seal is restored.'},
 {name:'Trisha',title:'Proof we were here',target:'item:keepsake',request:'There is an old photograph by the eastern house. Riri says it has one more person every time you count. Please bring it here.',ready:'You found the photograph. I am counting exactly once.',finish:'There are eighteen of us. We kept leaving space in the middle for you.',clue:'The gathering is not a memory of a place. It is a memory of people.'},
 {name:'Riri',title:'Bakery after closing',target:'room:0',request:'Someone is knocking from inside the first building. Go into the old home and investigate. I will stay here and provide moral support from a very safe distance.',ready:'You actually went in? Oh, that was not a bakery. I owe you an apology.',finish:'That note is from us. We left clues because we knew you would follow them.',clue:'The houses can remember things the streets cannot.'},
 {name:'Arsha',title:'Ticket for tomorrow',target:'item:ticket',request:'A ticket fell behind the platform benches. The date on it cannot be right. Find it before the train comes.',ready:'Tomorrow. It really does say tomorrow.',finish:'Maybe the train is not late. Maybe we have not reached the day it was waiting for.',clue:'The ticket says TOMORROW.'},
 {name:'Mashriq',title:'The empty bench',target:'item:bench',request:'Someone left a voice recording under the northern bench. The bench is empty, but I can hear a laugh. Check it.',ready:'You heard it too? Thank goodness.',finish:'That is our laughter. It plays before the joke happens. Time here is a terrible comedian.',clue:'A sound can arrive before its source.'},
 {name:'Shah',title:'Unclaimed luggage',target:'item:keepsake',request:'A bag near the far platform is tagged with your name. Check the luggage before it disappears again.',ready:'A postcard? It says "do not miss the stop that never existed."',finish:'I think the station was built to keep people from leaving too soon.',clue:'The last train cannot take a passenger who is still remembering.'},
 {name:'Aaron',title:'The unbeatable cabinet',target:'item:cabinet',request:'There is a cabinet southeast of the arcade. It beats everyone because nobody tries talking to it. Find out what it wants.',ready:'You got it to speak? I knew there was a person behind the high score.',finish:'Winning was never the point. It just wanted someone to ask if it was okay.',clue:'TALK and MEMORY are stronger than attacks here.'},
 {name:'Lakshay',title:'A high score that spells a name',target:'item:token',request:'Find the token near the arcade machine. The engraving is the clue to a high score nobody can beat.',ready:'The engraving says REMEMBER. Subtle, arcade. Very subtle.',finish:'I still won the rematch, by the way. The machine insists I lost, but it is biased.',clue:'The arcade password is REMEMBER.'},
 {name:'AK',title:'The prize nobody wanted',target:'item:keepsake',request:'Someone put a rubber duck in the prize area. Bring it back. I need proof that this place has completely lost its mind.',ready:'A rubber duck. At the end of the world. Incredible.',finish:'It squeaks when the Watcher is near. I refuse to explain how I know that.',clue:'Ordinary objects can warn you when the signal changes.'},
 {name:'Limin',title:'The charm in the undergrowth',target:'item:charm',request:'I dropped my charm near the southern trail. Nut says the forest stole it. Please find it before Nut starts negotiating with trees.',ready:'You found it! See, Nut? Not everything is a conspiracy.',finish:'Okay, it was a little bit a conspiracy. The charm was pointing toward you.',clue:'The charm vibrates in time with a familiar melody.'},
 {name:'Nut',title:'The tree that moves',target:'item:tree',request:'Go check the glowing tree in the northeast. It has moved three times since we got here. I have photographic evidence, except the photos also moved.',ready:'So it did move. THANK YOU.',finish:'The path changes when someone remembers it. We might be able to make a shortcut appear.',clue:'Restoring the forest memory rearranges its paths.'},
 {name:'Mira',title:'A map drawn from memory',target:'item:keepsake',request:'Find the torn map in the southern woods. The compass is useless, but the map might still remember the way.',ready:'The ink is moving. That is not how ink works.',finish:'Follow the melody, not the shadows. That is the route I drew before everything changed.',clue:'The familiar melody is the safe direction.'},
 {name:'Hannah',title:'The patient without a diagnosis',target:'item:file',request:'The west ward has a missing file. Find it. Every other record here has a birthday where a diagnosis should be.',ready:'The missing file is yours. No, wait. The name keeps changing.',finish:'It does not say what happened to you. It says who was there when you needed someone.',clue:'The hospital records birthdays, not illnesses.'},
 {name:'Cem',title:'Emergency light',target:'item:light',request:'The emergency light in the north wing keeps flashing a pattern. Inspect it before the power goes out again.',ready:'Three short, one long. It is trying to get our attention.',finish:'I thought I was the only one who remembered that song. Apparently the building does too.',clue:'The signal repeats whenever the corridor resets.'},
 {name:'Azrin',title:'A record with no number',target:'item:record',request:'There is an unnumbered record in the archive. I saw my reflection carrying it. Please find it.',ready:'That is the one. There is no number because it is not a recording of the past.',finish:'The seventh record is the person choosing to open the other six. It is Clar.',clue:'The seventh record is the player, not another cassette.'},
 {name:'Mukshanna',title:'The last terminal',target:'item:terminal',request:'The terminal to the northeast is still running. Inspect it. It should not be able to recognise us.',ready:'It greeted you by name. I think it has been waiting for you.',finish:'You can leave now. Or you can stay long enough to hear all the different endings. Either way, we will be here.',clue:'You do not need every ending to reach the birthday.'}
]
export const ANCHORS=[0,5,8,11,14,16]
export const PUZZLE_STEPS=[
 [{title:'THE CLOCKWORK SEAL',prompt:'The pedestal has a slot shaped like a clock hand.',requires:'0:clock',need:'Inspect the stopped clock near the southern lane.',choices:['Force the mechanism','Align the hand to eleven nineteen','Walk away'],answer:1,clue:'Yanaal remembers the exact time.'},{title:'THE FIRST ECHO',prompt:'A voice says: "A memory survives when..."',choices:['Someone remembers it','The clock breaks','It is hidden forever'],answer:0,clue:'Naidu left a letter about being remembered.'},{title:'THE TOWN REMEMBERS',prompt:'Which time does the town clock show?',choices:['11:19','12:00','03:33'],answer:0,clue:'Look at the stopped clock.'}],
 [{title:'TICKET MACHINE',prompt:'The terminal demands a ticket with a date that has not happened.',requires:'1:ticket',need:'Inspect the ticket by the southern platform.',choices:['Insert yesterday','Insert tomorrow','Insert a blank ticket'],answer:1,clue:'Arsha is waiting for a train from tomorrow.'},{title:'PLATFORM ECHO',prompt:'The loudspeaker plays laughter before anyone speaks. Which sound belongs to the future?',choices:['A departing whistle','A joke nobody has told','Footsteps already gone'],answer:1,clue:'Mashriq heard the laughter before the joke.'},{title:'ARRIVAL TIME',prompt:'The last train arrives...',choices:['Yesterday','Tomorrow','Never'],answer:1,clue:'Read the ticket again.'}],
 [{title:'PRIZE CIRCUIT',prompt:'The cabinet asks for the engraved token.',requires:'2:token',need:'Find the arcade token in the northeast.',choices:['INSERT COIN','REMEMBER','GAME OVER'],answer:1,clue:'Lakshay can help with the engraving.'},{title:'THE HIGH SCORE',prompt:'A ghost refuses to play. How do you proceed?',choices:['Talk to the ghost','Break the machine','Unplug the arcade'],answer:0,clue:'Aaron says the cabinet only wants to be heard.'},{title:'PASSWORD',prompt:'The cabinet demands a password.',choices:['GAME OVER','REMEMBER','RESET'],answer:1,clue:'The arcade token is engraved.'}],
 [{title:'LOST COMPASS',prompt:'The charm points toward a voice you recognise.',requires:'3:charm',need:'Recover Limin’s charm from the southern trail.',choices:['Follow the loudest voice','Follow the familiar melody','Follow the Watcher'],answer:1,clue:'Mira drew a map to the music.'},{title:'A PATH THAT MOVES',prompt:'The trees rearrange themselves. What stays constant?',choices:['The road signs','The melody','The shadows'],answer:1,clue:'Listen, do not look.'},{title:'FOREST COMPASS',prompt:'The compass spins. What should Clar follow?',choices:['The loudest voice','The familiar melody','The darkest path'],answer:1,clue:'Mira knows the route.'}],
 [{title:'PATIENT FILE',prompt:'The record has no diagnosis, only a date.',requires:'4:file',need:'Find the missing patient file in the west ward.',choices:['Read the birthday','Discard the record','Erase the name'],answer:0,clue:'Hannah has noticed the dates.'},{title:'CORRIDOR RESET',prompt:'The emergency lights flash again. How do you break the loop?',choices:['Follow the rhythm','Run toward the shadow','Turn out every light'],answer:0,clue:'Cem heard the same rhythm before.'},{title:'PATIENT HISTORY',prompt:'The patient file has no diagnosis. What is recorded instead?',choices:['A birthday','A room number','An expiration date'],answer:0,clue:'The ward records dates that matter.'}],
 [{title:'UNNUMBERED RECORD',prompt:'The terminal asks you to present the record with no number.',requires:'5:record',need:'Find the unnumbered record in the archive.',choices:['Present the record','Erase the index','Shut down the terminal'],answer:0,clue:'Azrin knows the unnumbered record.'},{title:'THE WATCHER',prompt:'The silhouette asks: "If I forget you, do I disappear?"',choices:['Tell it to be quiet','Promise to remember','Lie that it is not real'],answer:1,clue:'The Watcher is afraid of being forgotten.'},{title:'THE SEVENTH',prompt:'Six logs are recovered. What is the seventh record?',choices:['The Watcher','Clar herself','An empty file'],answer:1,clue:'The seventh record is the person reading the other six.'}]
]
export const ROOM_SCENES=[
 {name:'OLD HOME',before:'A place set for nineteen. One chair is still empty.',after:'The empty chair has a hand-written name tag: CLAR.',object:'A handwritten guest list'},
 {name:'RECORD SHOP',before:'An old cassette player hums beneath a stack of blank tapes.',after:'The blank tapes now carry dates and fragments of familiar laughter.',object:'A humming cassette'},
 {name:'CLOSED CAFÉ',before:'Someone abandoned a birthday candle beside two cold cups.',after:'The café is warm again. The candle burns without getting shorter.',object:'A birthday candle'},
 {name:'FORGOTTEN CLASSROOM',before:'The chalkboard lists eighteen names and one question mark.',after:'Someone has replaced the question mark with a heart.',object:'A chalkboard of names'},
 {name:'HIDDEN STORAGE',before:'Boxes marked DO NOT DELETE line the walls.',after:'The boxes have opened. They are full of letters, not files.',object:'A box of letters'}
]
export const ENDING_SCENES={
 dawn:['The sky stops flickering. For the first time, the streetlights turn off because morning has actually arrived.','WATCHER: I can never tell if the sun is a bug or a feature.','Clar keeps the memories, including the difficult ones. Tomorrow can begin.'],
 loop:['The clock strikes 11:19. Every familiar voice echoes from the start of the story.','WATCHER: Ah. The scenic route. Again.','Clar can choose a different path this time, carrying the knowledge of the last.'],
 shadow:['The Watcher stops running. Its silhouette seems smaller when it is not chasing anyone.','WATCHER: I remembered everyone except myself. That was embarrassing.','Clar does not need to solve every mystery to show someone kindness.'],
 escape:['A side door opens onto an impossible field of daylight. The air smells like rain.','WATCHER: For the record, that door was supposed to be locked.','Clar steps outside, but the people she met remain part of her story.'],
 forgotten:['The archive asks one final time: DELETE THIS MEMORY?','WATCHER: I will remember it for you. I think. I am famously unreliable.','Even after letting go, the kindness that shaped Clar has not disappeared.'],
 true:['Six recovered records float around the empty seventh slot. A name appears where the missing file should be.','WATCHER: The file was never lost. You were the one carrying it. I may have made this unnecessarily dramatic.','Every friend contributed a fragment. Together, they were not a record of Clar’s past, but a promise to be there for her future.']
}
